name: on_connectivity_widget
description: Flutter Package used to listen network connection and show a custom message to application.
version: 1.0.2+1
homepage: https://github.com/LucJosin/on_connectivity_widget
# pub.dev: https://pub.dev/packages/on_connectivity_widget
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  on_toast_widget: ^1.0.0
  connectivity_plus: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
